"""Spend categories: how each kind of vendor bills, and how its lines are normally coded."""

SITES = ["O'Fallon campus", "New York office", "Purchase data centre", "Kansas City data centre",
         "Waterloo office", "Pune GBSC", "Arlington office", "Miami hub", "Chicago office"]

HARDWARE_ITEMS = [
    # description, unit price range, asset class account (capitalised if >= threshold), weight
    ("Latitude 7450 laptop, 16GB RAM, 512GB SSD", (1_745, 1_895), "1540", 14),
    ("Latitude 5550 laptop, 16GB RAM, 256GB SSD", (1_180, 1_320), "1540", 10),
    ("Precision 5690 mobile workstation, 32GB RAM", (2_950, 3_400), "1540", 4),
    ("OptiPlex 7020 Micro desktop, 16GB RAM", (1_020, 1_140), "1540", 5),
    ("Precision 3680 tower workstation", (2_200, 2_650), "1540", 2),
    ("27\" UltraSharp U2724D monitor", (390, 450), "6360", 9),
    ("34\" curved monitor P3424WE", (520, 610), "6360", 3),
    ("Thunderbolt Dock WD22TB4", (255, 300), "6360", 8),
    ("Wireless keyboard and mouse combo KM7321W", (62, 80), "6360", 6),
    ("USB-C to HDMI adapter", (24, 32), "6360", 3),
    ("Laptop backpack 15\"", (48, 65), "6360", 2),
    ("PowerEdge R760 rack server, 2x Xeon Gold", (18_500, 24_000), "1545", 1),
    ("PowerVault ME5024 storage array", (21_000, 27_500), "1545", 1),
]

NETWORK_ITEMS = [
    ("Core switch 48-port 25GbE", (14_500, 17_800), "1530", 2),
    ("Access switch 48-port PoE+", (3_900, 4_600), "6360", 4),
    ("Wireless access point Wi-Fi 7", (690, 820), "6360", 5),
    ("Next-gen firewall appliance HA pair", (38_000, 46_000), "1530", 1),
    ("SFP28 transceiver module", (115, 160), "6360", 4),
]

FURNITURE_ITEMS = [
    ("Height-adjustable desk 160x80", (780, 960), "6460", 6),
    ("Ergonomic task chair", (640, 890), "6460", 6),
    ("Collaboration booth, 4-person", (14_800, 18_900), "1550", 1),
    ("Boardroom table 12-seat", (8_200, 11_600), "1550", 1),
    ("Pedestal storage unit", (210, 290), "6460", 4),
]

CATEGORIES = {
    "telecoms": {
        "label": "Telecommunications", "gl": "6310", "freq": "monthly", "vendor_count": 8,
        "ccs": [("CC4420", 6), ("CC4480", 2), ("CC9100", 2)],
        "median_range": (6_000, 48_000), "spread": 0.05, "lines": (2, 4),
        "templates": ["Monthly mobile service – {mon}", "Mobile data pooled plan – {mon}",
                      "MPLS circuit rental – {site} – {mon}", "SIP trunk service – {mon}",
                      "International roaming charges – {mon}", "Dedicated internet access 10Gbps – {mon}",
                      "Conference bridge usage – {mon}", "Device protection plan – {mon}"],
        "alt": [("6360", "Replacement handsets ({qty} units)")],
        "confusable": "6420", "po_share": 0.05,
        "names": (["Northgate", "Clearwave", "Ridgeline", "Harbor", "Bluepoint", "Silverline", "Tristate",
                   "Prairie"], ["Communications", "Telecom", "Networks", "Connect"]),
    },
    "saas": {
        "label": "Software subscriptions", "gl": "6350", "freq": "monthly_or_annual", "vendor_count": 55,
        "ccs": [("CC4450", 5), ("CC4460", 3), ("CC4440", 3), ("CC6110", 2), ("CC8100", 2), ("CC7150", 2),
                ("CC9130", 3), ("CC9110", 2), ("CC7110", 1)],
        "median_range": (1_200, 60_000), "spread": 0.08, "lines": (1, 3),
        "templates": ["Platform subscription – {mon}", "User licences ({qty} seats) – {mon}",
                      "Premium support tier – {mon}", "API usage overage – {mon}",
                      "Additional storage add-on – {mon}", "Sandbox environment licence – {mon}"],
        "annual_templates": ["Annual platform subscription {period}", "Enterprise licence renewal {period}",
                             "Annual support and maintenance {period}"],
        "alt": [("6510", "Implementation services – {qty} days")],
        "confusable": "6340", "po_share": 0.10,
        "names": (["Skyloft", "Datavault", "Quantia", "Synapsis", "Brightlane", "Corelytics", "Ledgerly",
                   "Vantix", "Opalstone", "Nimbusly", "Fieldmark", "Signalpath", "Clearbook", "Trellis",
                   "Kitebridge", "Ampliqo", "Northwind Logic", "Haldane", "Veritaq", "Pivotra"],
                  ["Analytics", "Software", "Systems", "Labs", "Cloud", "Technologies", "HQ"]),
    },
    "cloud": {
        "label": "Cloud & hosting", "gl": "6340", "freq": "monthly", "vendor_count": 6,
        "ccs": [("CC4430", 6), ("CC4460", 2), ("CC9110", 2)],
        "median_range": (18_000, 240_000), "spread": 0.12, "lines": (2, 5),
        "templates": ["Compute instances – {mon}", "Object storage – {mon}", "Managed database service – {mon}",
                      "Data egress – {mon}", "Colocation rack space – {site} – {mon}",
                      "Content delivery network – {mon}", "Backup and DR service – {mon}"],
        "alt": [], "confusable": "6350", "po_share": 0.20,
        "names": (["Stratus", "Ironpeak", "Helix", "Bluehaven", "Coldspring", "Meridian Grid"],
                  ["Cloud", "Hosting", "Data Centers", "Infrastructure"]),
    },
    "it_hardware": {
        "label": "IT hardware", "gl": "1540", "freq": "irregular", "vendor_count": 10,
        "ccs": [("CC4410", 7), ("CC4490", 2), ("CC4420", 2), ("CC4470", 1)],
        "median_range": (8_000, 60_000), "spread": 0.6, "lines": (1, 4), "items": "hardware",
        "alt": [], "confusable": "6420", "po_share": 0.88,
        "names": (["Pinnacle", "Corelink", "Apex", "Vertex", "Summitview", "Brightstar", "Ironclad",
                   "Keystone", "Novaline"], ["IT Solutions", "Computer Supply", "Technology Partners",
                                             "Systems Integration"]),
    },
    "network_hw": {
        "label": "Network equipment", "gl": "1530", "freq": "irregular", "vendor_count": 4,
        "ccs": [("CC4480", 6), ("CC4420", 2)],
        "median_range": (10_000, 90_000), "spread": 0.6, "lines": (1, 3), "items": "network",
        "alt": [], "confusable": "6420", "po_share": 0.92,
        "names": (["Backbone", "Arcwire", "Packetline", "Crossfield"], ["Networks", "Network Supply"]),
    },
    "it_services": {
        "label": "IT maintenance & support", "gl": "6420", "freq": "monthly", "vendor_count": 25,
        "ccs": [("CC4420", 4), ("CC4410", 3), ("CC4450", 2), ("CC4480", 2), ("CC4470", 1)],
        "median_range": (2_500, 35_000), "spread": 0.15, "lines": (1, 3),
        "templates": ["Hardware maintenance contract – {mon}", "On-site break/fix support – {mon}",
                      "Printer fleet managed service – {mon}", "UPS preventive maintenance – {site}",
                      "Storage array support renewal – {mon}", "Desk-side support T&M – {qty} hours",
                      "Laptop screen and keyboard repairs ({qty} units)"],
        "alt": [("6530", "Field engineer – {qty} days")], "confusable": "1540", "po_share": 0.30,
        "names": (["Reliant", "Fixwell", "Uptime", "Continuum", "Servicepoint", "Ironbridge", "Northstar",
                   "Allied", "Precision", "Proactive", "Sterling", "Frontline"],
                  ["IT Services", "Support Services", "Technical Services", "Managed Services"]),
    },
    "facilities": {
        "label": "Facilities services", "gl": "6430", "freq": "monthly", "vendor_count": 30,
        "ccs": [("CC5200", 6), ("CC5210", 3), ("CC5250", 3), ("CC5220", 1), ("CC5230", 1)],
        "median_range": (1_800, 42_000), "spread": 0.08, "lines": (1, 3),
        "templates": ["Janitorial services – {site} – {mon}", "HVAC preventive maintenance – {mon}",
                      "Landscaping and grounds – {mon}", "Waste and recycling collection – {mon}",
                      "Pest control – {site} – {mon}", "Elevator maintenance contract – {mon}",
                      "Window cleaning – {site}", "Plant care service – {mon}"],
        "adhoc_templates": ["On-site HVAC repair – {site}", "Emergency plumbing works – {site}",
                            "Roof leak repair – {site}", "Generator call-out and repair – {site}"],
        "alt": [("6420", "On-site HVAC repair – {site}")], "confusable": "6420", "po_share": 0.12,
        "names": (["Pinecrest", "Greenfield", "Crestline", "Everclean", "Harbourview", "Brightway", "Oakmont",
                   "Riverbend", "Cornerstone", "Prestige", "Lakeside", "Maplewood"],
                  ["Facility Services", "Building Services", "Property Services", "Maintenance Co."]),
    },
    "utilities": {
        "label": "Utilities", "gl": "6440", "freq": "monthly", "vendor_count": 12,
        "ccs": [("CC5200", 5), ("CC5210", 2), ("CC5220", 1), ("CC5230", 1)],
        "median_range": (3_000, 95_000), "spread": 0.14, "lines": (1, 2),
        "templates": ["Electricity supply – {site} – {mon}", "Natural gas – {site} – {mon}",
                      "Water and sewer – {site} – {mon}", "Chilled water service – {site} – {mon}"],
        "alt": [], "confusable": "6430", "po_share": 0.0,
        "names": (["Midstate", "Riverside", "Ameri", "Prairie", "Gateway", "Lakeland", "Heartland"],
                  ["Power & Light", "Energy", "Gas Co.", "Water Authority", "Utilities"]),
    },
    "security": {
        "label": "Security services", "gl": "6450", "freq": "monthly", "vendor_count": 6,
        "ccs": [("CC5240", 6), ("CC5200", 1)],
        "median_range": (12_000, 85_000), "spread": 0.06, "lines": (1, 3),
        "templates": ["Manned guarding – {site} – {mon}", "Alarm monitoring – {mon}",
                      "CCTV maintenance – {site}", "Executive protection detail – {mon}",
                      "Access control system support – {mon}"],
        "alt": [], "confusable": "6430", "po_share": 0.40,
        "names": (["Sentinel", "Guardline", "Bastion", "Ironwatch", "Shieldpoint", "Vigil"],
                  ["Security", "Protective Services", "Security Group"]),
    },
    "consulting": {
        "label": "Consulting", "gl": "6510", "freq": "irregular", "vendor_count": 35,
        "ccs": [("CC7100", 3), ("CC7150", 2), ("CC7140", 2), ("CC9110", 2), ("CC4450", 2), ("CC8100", 1),
                ("CC9130", 2), ("CC5120", 1)],
        "median_range": (8_000, 140_000), "spread": 0.35, "lines": (1, 3),
        "templates": ["Process-mapping workshop – {mon}", "Operating model design – phase {n}",
                      "Advisory services – {mon}", "Programme management office – {mon}",
                      "Data strategy assessment", "Controls design review – {mon}",
                      "Change management support – {mon}", "Target operating model – phase {n}"],
        "alt": [("6710", "Consultant travel expenses – {mon}")], "confusable": "6530", "po_share": 0.55,
        "names": (["Clearpath", "Kestrel", "Halden", "Northbridge", "Ardent", "Calloway", "Westmere",
                   "Lindqvist", "Ashgrove", "Fairhaven", "Thornbury", "Marlowe", "Penrose", "Sable"],
                  ["Advisory", "Consulting", "Partners", "Group", "Associates"]),
    },
    "audit_tax": {
        "label": "Audit & tax advisory", "gl": "6520", "freq": "irregular", "vendor_count": 6,
        "ccs": [("CC7130", 4), ("CC7150", 3), ("CC7160", 2)],
        "median_range": (25_000, 220_000), "spread": 0.3, "lines": (1, 2),
        "templates": ["Transfer pricing documentation FY{fy}", "Indirect tax advisory – {mon}",
                      "SOX readiness support – {mon}", "Statutory audit fee – interim billing {n}",
                      "R&D tax credit study FY{fy}"],
        "alt": [], "confusable": "6510", "po_share": 0.15,
        "names": (["Whitcombe", "Grayson Ellery", "Holbrook", "Ainsley Varga", "Redfern", "Castell"],
                  ["LLP", "& Co. LLP", "Tax Advisors"]),
    },
    "contract_labour": {
        "label": "Contract labour", "gl": "6530", "freq": "monthly", "vendor_count": 25,
        "ccs": [("CC9110", 3), ("CC4450", 3), ("CC7110", 2), ("CC7170", 2), ("CC9120", 2), ("CC4470", 1)],
        "median_range": (6_000, 120_000), "spread": 0.12, "lines": (1, 4),
        "templates": ["Contractor timesheets w/e {wk} – {qty} hours", "Software engineer contractor – {mon}",
                      "AP clerk temporary staff – {mon}", "QA test analyst – {mon}",
                      "Project coordinator contractor – {mon}", "Data engineer contractor – {mon}"],
        "alt": [], "confusable": "6510", "po_share": 0.70,
        "names": (["Talentbridge", "Workforce One", "Staffwise", "Peoplelink", "Crewmark", "Skillhaus",
                   "Bench Street", "Rapid Talent"], ["Staffing", "Resourcing", "Solutions", "Talent"]),
    },
    "legal": {
        "label": "Legal services", "gl": "6610", "freq": "irregular", "vendor_count": 22,
        "ccs": [("CC5100", 9), ("CC5120", 2), ("CC5130", 1)],
        "median_range": (12_000, 160_000), "spread": 0.45, "lines": (1, 3),
        "templates": ["Legal services – {matter_desc} – {matter}", "Professional fees – matter {matter}",
                      "Disbursements – matter {matter}", "Regulatory advice – {matter}",
                      "Litigation support – {matter}"],
        "alt": [], "confusable": "6510", "po_share": 0.0,
        "names": (["Ashby Lowe", "Ellison Crane", "Mortimer Shaw", "Vance Holloway", "Pryor Whitley",
                   "Delacroix Marsh", "Kingsley Rourke", "Abernathy", "Sloane Pettigrew", "Halloran Beck"],
                  ["LLP", "& Partners LLP", "Law Group"]),
    },
    "marketing": {
        "label": "Marketing services", "gl": "6810", "freq": "irregular", "vendor_count": 30,
        "ccs": [("CC6100", 4), ("CC6110", 4), ("CC6130", 2), ("CC6140", 1)],
        "median_range": (5_000, 180_000), "spread": 0.45, "lines": (1, 4),
        "templates": ["Creative production – campaign {ref}", "Paid social media management – {mon}",
                      "Media buying – {mon}", "Brand tracking research – wave {n}",
                      "Agency retainer – {mon}", "Content production – {qty} assets", "SEO services – {mon}"],
        "alt": [("6480", "Print collateral – {qty} units")], "confusable": "6820", "po_share": 0.45,
        "names": (["Foxglove", "Lumen", "Redbird", "Tandem", "Kindred", "Paperkite", "Vivid Harbor",
                   "Bold North", "Mosaic", "Coastline"], ["Creative", "Agency", "Media", "Studio", "Collective"]),
    },
    "events": {
        "label": "Events & sponsorships", "gl": "6820", "freq": "irregular", "vendor_count": 15,
        "ccs": [("CC6120", 7), ("CC6130", 1), ("CC8100", 1)],
        "median_range": (8_000, 220_000), "spread": 0.5, "lines": (1, 4),
        "templates": ["Venue hire – {event}", "Booth build and dismantle – {event}",
                      "Event production and AV – {event}", "Sponsorship package – {event}",
                      "Delegate catering – {event}"],
        "alt": [("6720", "Delegate catering – {event}")], "confusable": "6810", "po_share": 0.50,
        "names": (["Grandstand", "Eventwise", "Stagecraft", "Pavilion", "Marquee", "Convene"],
                  ["Events", "Productions", "Venues", "Experiences"]),
    },
    "training": {
        "label": "Training", "gl": "6910", "freq": "irregular", "vendor_count": 20,
        "ccs": [("CC8120", 6), ("CC4440", 1), ("CC7100", 1), ("CC7170", 1)],
        "median_range": (1_500, 45_000), "spread": 0.4, "lines": (1, 2),
        "templates": ["Leadership programme – cohort {n}", "Course: {course} ({qty} delegates)",
                      "E-learning library licence – {mon}", "Certification exam vouchers ({qty})",
                      "Facilitated workshop – {course}"],
        "alt": [], "confusable": "6510", "po_share": 0.20,
        "names": (["Learnwell", "Skillforge", "Mentorly", "Brightmind", "Pathwise", "Cadence"],
                  ["Learning", "Academy", "Training Group", "Institute"]),
    },
    "office_supplies": {
        "label": "Office supplies", "gl": "6460", "freq": "monthly", "vendor_count": 10,
        "ccs": [("CC5250", 5), ("CC5200", 2), ("CC5230", 1)],
        "median_range": (600, 9_000), "spread": 0.25, "lines": (2, 6),
        "templates": ["Copier paper A4/Letter ({qty} cases)", "Stationery – {mon}", "Toner cartridges ({qty})",
                      "Pantry supplies – {mon}", "Breakroom coffee service – {mon}", "Ergonomic accessories"],
        "alt": [("6360", "USB-C chargers ({qty})")], "confusable": "6360", "po_share": 0.25,
        "names": (["Officeline", "Deskright", "Supplyhouse", "Papermill", "Allstar"],
                  ["Office Supply", "Supplies", "Business Products"]),
    },
    "courier": {
        "label": "Postage & courier", "gl": "6470", "freq": "monthly", "vendor_count": 8,
        "ccs": [("CC5250", 4), ("CC7110", 2), ("CC5100", 1)],
        "median_range": (400, 12_000), "spread": 0.2, "lines": (1, 2),
        "templates": ["Courier shipments – {mon}", "Overnight document delivery – {mon}",
                      "International express – {mon}", "Mailroom franking – {mon}"],
        "alt": [], "confusable": "6430", "po_share": 0.0,
        "names": (["Swiftline", "Parcelpoint", "Rapidroute", "Nightjet", "Courierco"],
                  ["Express", "Logistics", "Couriers"]),
    },
    "memberships": {
        "label": "Dues & memberships", "gl": "6930", "freq": "annual", "vendor_count": 12,
        "ccs": [("CC7150", 2), ("CC5120", 2), ("CC9140", 2), ("CC7130", 1), ("CC9900", 1)],
        "median_range": (2_500, 75_000), "spread": 0.05, "lines": (1, 1),
        "templates": ["Annual corporate membership {period}", "Professional body subscriptions {period}",
                      "Industry forum membership {period}"],
        "alt": [], "confusable": "6350", "po_share": 0.0,
        "names": (["Payments Council", "Treasury Forum", "Fraud Prevention Alliance", "Finance Leaders",
                   "Shared Services Network"], ["Association", "Institute", "Forum"]),
    },
    "insurance": {
        "label": "Insurance", "gl": "6940", "freq": "annual", "vendor_count": 5,
        "ccs": [("CC7120", 4), ("CC9900", 1)],
        "median_range": (40_000, 650_000), "spread": 0.05, "lines": (1, 2),
        "templates": ["Cyber liability premium {period}", "Directors & officers premium {period}",
                      "Property all-risks premium {period}", "Crime and fidelity premium {period}"],
        "alt": [], "confusable": "6350", "po_share": 0.0,
        "names": (["Granite Mutual", "Aldridge", "Beaconfield", "Harrowgate", "Atlas Marine"],
                  ["Insurance", "Underwriters", "Assurance"]),
    },
    "recruitment": {
        "label": "Recruitment", "gl": "6920", "freq": "irregular", "vendor_count": 12,
        "ccs": [("CC8110", 7), ("CC9110", 1)],
        "median_range": (9_000, 60_000), "spread": 0.35, "lines": (1, 1),
        "templates": ["Placement fee – {role}", "Retained search – {role} – instalment {n}",
                      "Job board advertising – {mon}", "Background screening – {qty} candidates"],
        "alt": [], "confusable": "6530", "po_share": 0.20,
        "names": (["Hirewell", "Talentscope", "Executive Search Partners", "Candor", "Headway", "Quarry"],
                  ["Search", "Recruitment", "Talent Partners"]),
    },
    "catering": {
        "label": "Meals & catering", "gl": "6720", "freq": "monthly", "vendor_count": 12,
        "ccs": [("CC5250", 4), ("CC6120", 2), ("CC8120", 1)],
        "median_range": (800, 28_000), "spread": 0.2, "lines": (1, 3),
        "templates": ["Meeting catering – {mon}", "Cafeteria subsidy – {site} – {mon}",
                      "Working lunch – {event}", "Executive dining – {mon}"],
        "alt": [], "confusable": "6820", "po_share": 0.05,
        "names": (["Harvest Table", "Copper Kettle", "Greenleaf", "Saffron", "Baker Street", "Fresh Fork"],
                  ["Catering", "Food Services", "Kitchens"]),
    },
    "furniture": {
        "label": "Furniture & fit-out", "gl": "1550", "freq": "irregular", "vendor_count": 6,
        "ccs": [("CC5200", 3), ("CC5210", 2), ("CC5250", 2), ("CC5230", 1)],
        "median_range": (6_000, 120_000), "spread": 0.6, "lines": (1, 4), "items": "furniture",
        "alt": [], "confusable": "6430", "po_share": 0.85,
        "names": (["Workform", "Fulcrum", "Studio Oak", "Ergonest", "Spacecraft", "Modulo"],
                  ["Furniture", "Interiors", "Workplace"]),
    },
    "market_data": {
        "label": "Market data", "gl": "6370", "freq": "monthly", "vendor_count": 8,
        "ccs": [("CC7120", 3), ("CC9130", 3), ("CC9140", 2)],
        "median_range": (4_000, 70_000), "spread": 0.04, "lines": (1, 3),
        "templates": ["Market data terminal licences ({qty}) – {mon}", "FX rates feed – {mon}",
                      "Credit ratings data licence – {mon}", "BIN and issuer data feed – {mon}"],
        "alt": [], "confusable": "6350", "po_share": 0.10,
        "names": (["Tickstream", "Ratewise", "Ledgerpoint", "Indexa", "Quotient", "Clearprice"],
                  ["Data", "Information Services", "Markets"]),
    },
    "printing": {
        "label": "Printing", "gl": "6480", "freq": "irregular", "vendor_count": 8,
        "ccs": [("CC6100", 3), ("CC5250", 2), ("CC6120", 1)],
        "median_range": (900, 22_000), "spread": 0.4, "lines": (1, 3),
        "templates": ["Brochure print run ({qty} units)", "Business cards ({qty} sets)",
                      "Event signage – {event}", "Large-format printing – {site}"],
        "alt": [], "confusable": "6810", "po_share": 0.15,
        "names": (["Inkwell", "Pressline", "Printcraft", "Folio", "Sharpline"], ["Print", "Press", "Graphics"]),
    },
    "research": {
        "label": "Research & advisory", "gl": "6540", "freq": "annual", "vendor_count": 10,
        "ccs": [("CC4450", 2), ("CC9110", 2), ("CC7140", 1), ("CC9900", 1), ("CC4440", 1)],
        "median_range": (18_000, 160_000), "spread": 0.05, "lines": (1, 2),
        "templates": ["Research subscription {period}", "Analyst advisory seats ({qty}) {period}",
                      "Benchmarking study access {period}"],
        "alt": [], "confusable": "6350", "po_share": 0.10,
        "names": (["Foresight", "Meridian Insight", "Clearview", "Benchline", "Stratagem"],
                  ["Research", "Advisory", "Insights"]),
    },
    "translation": {
        "label": "Translation", "gl": "6550", "freq": "irregular", "vendor_count": 5,
        "ccs": [("CC5130", 2), ("CC6140", 2), ("CC5120", 1)],
        "median_range": (1_200, 18_000), "spread": 0.4, "lines": (1, 2),
        "templates": ["Document translation – {qty} words", "Interpreting services – {event}",
                      "Localisation – product release {ref}"],
        "alt": [], "confusable": "6510", "po_share": 0.05,
        "names": (["Lingua", "Polyglot", "Wordbridge", "Tessera", "Babelpoint"], ["Translations", "Language Services"]),
    },
}

LEGAL_MATTERS = [
    ("M-2207", "Supplier contract review", "Commercial"),
    ("M-2188", "Data processing agreement renegotiation", "Privacy"),
    ("M-2214", "Network rules regulatory filing", "Regulatory"),
    ("M-2156", "Employment dispute – EU01", "Employment"),
    ("M-2231", "Patent portfolio maintenance", "IP"),
    ("M-2203", "Merchant litigation – class action defence", "Litigation"),
    ("M-2179", "Open banking partnership terms", "Commercial"),
    ("M-2241", "Real estate lease – Arlington", "Real Estate"),
    ("M-2162", "Anti-money-laundering programme review", "Regulatory"),
    ("M-2195", "Cloud services master agreement", "Commercial"),
    ("M-2226", "Trademark opposition – APAC", "IP"),
    ("M-2170", "Sanctions compliance advice", "Regulatory"),
    ("M-2249", "Acquisition due diligence – Project Lark", "M&A"),
    ("M-2183", "Data breach response readiness", "Privacy"),
    ("M-2236", "Interchange fee consultation response", "Regulatory"),
    ("M-2153", "Supplier insolvency – claim filing", "Litigation"),
    ("M-2219", "Marketing promotions compliance", "Commercial"),
    ("M-2244", "Pune office lease renewal", "Real Estate"),
    ("M-2191", "Tokenisation patent licensing", "IP"),
    ("M-2228", "Card scheme rules dispute", "Litigation"),
    ("M-2167", "Whistleblower investigation", "Employment"),
    ("M-2252", "AI governance policy review", "Regulatory"),
    ("M-2174", "Vendor master services template refresh", "Commercial"),
    ("M-2209", "Cross-border data transfer assessment", "Privacy"),
    ("M-2238", "Sponsorship agreement – global football", "Commercial"),
    ("M-2159", "Tax controversy support – EU01", "Tax"),
    ("M-2246", "Fintech minority investment", "M&A"),
    ("M-2185", "Consumer protection enquiry", "Regulatory"),
    ("M-2222", "Software licence audit defence", "Commercial"),
    ("M-2198", "Benefits plan amendments", "Employment"),
    ("M-2233", "Biometric authentication patent", "IP"),
    ("M-2165", "Debt collection agency contract", "Commercial"),
    ("M-2211", "Market conduct review", "Regulatory"),
    ("M-2254", "Joint venture formation – LATAM", "M&A"),
    ("M-2177", "Contractor misclassification review", "Employment"),
    ("M-2201", "Copyright takedown programme", "IP"),
    ("M-2225", "Payment facilitator onboarding terms", "Commercial"),
    ("M-2193", "Cyber incident regulatory notification", "Privacy"),
    ("M-2240", "Chargeback arbitration – acquirer", "Litigation"),
    ("M-2216", "Office relocation – New York", "Real Estate"),
]

EVENTS = ["Payments Innovation Summit", "Global Partner Forum", "Fintech Week Europe", "Customer Advisory Board",
          "GBSC Town Hall", "Developer Conference", "Risk & Fraud Symposium", "Sales Kick-off"]
COURSES = ["Advanced Excel for Finance", "IFRS 16 Leases", "SOX Controls Fundamentals", "Cloud Security Essentials",
           "Agile Product Ownership", "Negotiation Skills", "Data Literacy", "Power BI for Analysts"]
ROLES = ["Senior Product Manager", "Director of Data Engineering", "Treasury Analyst", "Cyber Threat Lead",
         "Head of Partner Marketing", "Principal Software Engineer", "Tax Manager", "Regional Counsel"]
