// Architecture content. Component names, files and flows mirror backend/ and vercel.json; cloud proposals map each
// as-built component to its AWS and Azure counterpart.

export type NodeKind = 'person' | 'ui' | 'edge' | 'app' | 'agent' | 'model' | 'data' | 'ext' | 'ops'
export type DNode = { id: string; label: string; sub?: string; col: number; row: number; w?: number; kind: NodeKind; ai?: boolean }
export type Zone = { label: string; col: number; row: number; w: number; h: number; kind: 'client' | 'tenant' | 'model' | 'public' | 'corp' }
export type Flow = { from: string; to: string; n: number; label: string; data: 'Confidential' | 'Internal' | 'Public' }
export type Diagram = { id: string; title: string; summary: string; cols: number; rows: number; zones: Zone[]; nodes: DNode[]; flows: Flow[]; notes: string[] }

export const AS_BUILT: Diagram = {
  id: 'repo', title: 'How this demo is built',
  summary: 'One React app and one Python service. The agent runtime, every check and the model calls run inside the service; state is an append-only event log plus run records. Everything outside the dashed line is a public service called over HTTPS.',
  cols: 5, rows: 4,
  zones: [
    { label: 'Browser', col: 0, row: 0, w: 1, h: 4, kind: 'client' },
    { label: 'Vercel project (demo tenant)', col: 1, row: 0, w: 3, h: 4, kind: 'tenant' },
    { label: 'Public services', col: 4, row: 0, w: 1, h: 4, kind: 'public' },
  ],
  nodes: [
    { id: 'people', label: 'Reviewers, approvers, controllers', sub: 'Named sign-in, role-aware', col: 0, row: 0, kind: 'person' },
    { id: 'spa', label: 'React workspace', sub: 'web/src · Vite build', col: 0, row: 1, kind: 'ui' },
    { id: 'phone', label: 'Requester phone view', sub: 'QR code, no install', col: 0, row: 2, kind: 'ui' },
    { id: 'cdn', label: 'Vercel CDN + rewrites', sub: 'vercel.json · noindex', col: 1, row: 0, kind: 'edge' },
    { id: 'api', label: 'FastAPI service', sub: 'backend/app.py · passcode + session + roles', col: 1, row: 1, kind: 'app' },
    { id: 'svc', label: 'Demo service', sub: 'service.py · runs, decisions, cases, SLAs', col: 1, row: 2, kind: 'app' },
    { id: 'sup', label: 'Supervisor + 6 specialist agents', sub: 'backend/agents · fixed order', col: 2, row: 1, kind: 'agent', ai: true },
    { id: 'tools', label: 'Tool registry (40+ tools)', sub: 'agents/tools.py · typed, recorded', col: 2, row: 2, kind: 'agent' },
    { id: 'inv', label: 'Investigator', sub: 'Claude tool loop, read-only', col: 2, row: 0, kind: 'agent', ai: true },
    { id: 'model', label: 'Coding model', sub: 'champion + challenger, calibrated', col: 3, row: 1, kind: 'model' },
    { id: 'seed', label: 'Reference data', sub: '12k invoices · 5k POs · 4k journals · 11k receipts', col: 3, row: 2, kind: 'data' },
    { id: 'state', label: 'Event log + run records', sub: 'state.py · SQLite / Neon Postgres', col: 2, row: 3, kind: 'data' },
    { id: 'files', label: 'R12 interface files', sub: 'AP_INVOICES, GL_INTERFACE, reapplication', col: 1, row: 3, kind: 'data' },
    { id: 'cache', label: 'Model response cache', sub: 'data/cache · replay mode', col: 3, row: 3, kind: 'data' },
    { id: 'claude', label: 'Claude API', sub: 'Opus 5.5 · read, explain, investigate', col: 4, row: 0, kind: 'ext', ai: true },
    { id: 'vies', label: 'EU VIES · OFAC · ECB FX', sub: 'tax, sanctions, rates', col: 4, row: 1, kind: 'ext' },
  ],
  flows: [
    { from: 'spa', to: 'cdn', n: 1, label: 'Page and API requests over HTTPS; session cookie', data: 'Internal' },
    { from: 'cdn', to: 'api', n: 2, label: '/api/* rewritten to the Python function', data: 'Internal' },
    { from: 'api', to: 'svc', n: 3, label: 'Role check on every action; refusals audited', data: 'Internal' },
    { from: 'svc', to: 'sup', n: 4, label: 'Run the invoice: events streamed back over SSE', data: 'Confidential' },
    { from: 'sup', to: 'tools', n: 5, label: 'Every check is a recorded tool call', data: 'Confidential' },
    { from: 'tools', to: 'model', n: 6, label: 'Score accounts; calibrated confidence + second opinion', data: 'Confidential' },
    { from: 'tools', to: 'seed', n: 7, label: 'History, vendors, POs, contracts, policies', data: 'Confidential' },
    { from: 'sup', to: 'claude', n: 8, label: 'PDF read and reviewer reason (schema-bound)', data: 'Confidential' },
    { from: 'inv', to: 'claude', n: 9, label: 'Exception investigation with read-only tools', data: 'Confidential' },
    { from: 'tools', to: 'vies', n: 10, label: 'VAT, sanctions, FX lookups (no client data beyond the tax ID)', data: 'Public' },
    { from: 'svc', to: 'state', n: 11, label: 'Runs, decisions, cases, policy versions, audit events', data: 'Confidential' },
    { from: 'svc', to: 'files', n: 12, label: 'Approved invoices and corrections as interface files', data: 'Confidential' },
    { from: 'phone', to: 'api', n: 13, label: 'Requester confirms receipt', data: 'Internal' },
  ],
  notes: [
    'Claude never picks the GL account: the scoring engine does, and every recommendation cites the past invoices behind it.',
    'If the model is unreachable the run completes: extraction falls back to the intake record, the reason and the investigation to deterministic summaries.',
    'The agents can recommend, hold and route. Approvals, corrections and policy changes are people, checked by role on the server.',
  ],
}

export const BEDROCK: Diagram = {
  id: 'aws', title: 'Proposed on Amazon Bedrock',
  summary: 'The same service in a container inside the client VPC. Specialists become Bedrock collaborator agents whose action groups are the existing tools, Claude is served in-region from Bedrock, and Step Functions holds the waits on people. Nothing leaves the account except to Bedrock and the public registries.',
  cols: 5, rows: 4,
  zones: [
    { label: 'Mastercard network', col: 0, row: 0, w: 1, h: 4, kind: 'corp' },
    { label: 'AWS account · client VPC', col: 1, row: 0, w: 3, h: 4, kind: 'tenant' },
    { label: 'Amazon Bedrock (same region)', col: 4, row: 0, w: 1, h: 2, kind: 'model' },
    { label: 'Public', col: 4, row: 2, w: 1, h: 2, kind: 'public' },
  ],
  nodes: [
    { id: 'people', label: 'Finance users', sub: 'Corporate IdP → Cognito (SAML)', col: 0, row: 0, kind: 'person' },
    { id: 'mail', label: 'AP mailbox', sub: 'SES inbound → S3', col: 0, row: 1, kind: 'ui' },
    { id: 'erp', label: 'Oracle EBS R12', sub: 'Open interfaces via PrivateLink', col: 0, row: 3, kind: 'ext' },
    { id: 'edge', label: 'CloudFront + WAF + API Gateway', sub: 'S3 static site, private VPC link', col: 1, row: 0, kind: 'edge' },
    { id: 'svc', label: 'FastAPI on ECS Fargate', sub: 'same container as the demo', col: 1, row: 1, kind: 'app' },
    { id: 'sfn', label: 'Step Functions', sub: 'receipt and approval waits (task tokens)', col: 1, row: 2, kind: 'app' },
    { id: 'evb', label: 'EventBridge Scheduler', sub: 'month-end sweep, daily cash run', col: 1, row: 3, kind: 'ops' },
    { id: 'agents', label: 'Bedrock Agents', sub: 'supervisor + collaborators', col: 2, row: 0, kind: 'agent', ai: true },
    { id: 'lambda', label: 'Action groups on Lambda', sub: 'Checks, Policy, Recommender as tools', col: 2, row: 1, kind: 'agent' },
    { id: 'aurora', label: 'Aurora PostgreSQL', sub: 'runs, decisions, cases, audit', col: 2, row: 2, kind: 'data' },
    { id: 's3', label: 'S3 (Object Lock)', sub: 'PDFs, invocation logs, evidence packs', col: 2, row: 3, kind: 'data' },
    { id: 'kb', label: 'Knowledge Bases + OpenSearch', sub: 'policy grounding, history index', col: 3, row: 1, kind: 'data' },
    { id: 'obs', label: 'CloudWatch · CloudTrail · KMS', sub: 'metrics, audit, keys', col: 3, row: 3, kind: 'ops' },
    { id: 'claude', label: 'Claude on Bedrock', sub: 'in-region, no training on client data', col: 4, row: 0, kind: 'model', ai: true },
    { id: 'guard', label: 'Bedrock Guardrails', sub: 'PII, grounding, denied topics', col: 4, row: 1, kind: 'model' },
    { id: 'pub', label: 'EU VIES · OFAC · ECB', sub: 'via NAT, allow-listed', col: 4, row: 2, kind: 'ext' },
  ],
  flows: [
    { from: 'people', to: 'edge', n: 1, label: 'SSO session; roles from IdP groups', data: 'Internal' },
    { from: 'mail', to: 'svc', n: 2, label: 'New invoice event (S3 put → EventBridge)', data: 'Confidential' },
    { from: 'edge', to: 'svc', n: 3, label: 'API calls through the VPC link', data: 'Internal' },
    { from: 'svc', to: 'agents', n: 4, label: 'InvokeAgent per invoice', data: 'Confidential' },
    { from: 'agents', to: 'lambda', n: 5, label: 'Action group calls (typed tools)', data: 'Confidential' },
    { from: 'agents', to: 'claude', n: 6, label: 'Reasoning, extraction, reasons', data: 'Confidential' },
    { from: 'claude', to: 'guard', n: 7, label: 'Every response passes guardrails', data: 'Confidential' },
    { from: 'lambda', to: 'kb', n: 8, label: 'Similar lines, policy passages', data: 'Confidential' },
    { from: 'svc', to: 'aurora', n: 9, label: 'State and audit events', data: 'Confidential' },
    { from: 'svc', to: 'sfn', n: 10, label: 'Start wait; resume on confirm or approve', data: 'Internal' },
    { from: 'evb', to: 'svc', n: 11, label: 'Scheduled sweeps', data: 'Internal' },
    { from: 'svc', to: 'erp', n: 12, label: 'AP and GL interface batches', data: 'Confidential' },
    { from: 'lambda', to: 'pub', n: 13, label: 'Registry lookups', data: 'Public' },
    { from: 'svc', to: 's3', n: 14, label: 'Documents and evidence, retained', data: 'Confidential' },
  ],
  notes: [
    'Lowest-risk first step: run the current orchestrator on Bedrock AgentCore Runtime, then split into collaborator agents once the tools are stable.',
    'The tool contracts in backend/agents/tools.py already have the shape of action-group schemas; no logic is rewritten.',
  ],
}

export const FOUNDRY: Diagram = {
  id: 'azure', title: 'Proposed on Azure AI Foundry',
  summary: 'The same split on Microsoft’s stack, where identity, mail and approvals already live in Microsoft 365. Foundry Agent Service runs the supervisor and connected agents, Claude is served from Foundry, and Teams carries receipt confirmation and approval.',
  cols: 5, rows: 4,
  zones: [
    { label: 'Microsoft 365 tenant', col: 0, row: 0, w: 1, h: 4, kind: 'corp' },
    { label: 'Azure subscription · VNet', col: 1, row: 0, w: 3, h: 4, kind: 'tenant' },
    { label: 'Azure AI Foundry', col: 4, row: 0, w: 1, h: 2, kind: 'model' },
    { label: 'Public', col: 4, row: 2, w: 1, h: 2, kind: 'public' },
  ],
  nodes: [
    { id: 'people', label: 'Finance users', sub: 'Entra ID SSO, app roles', col: 0, row: 0, kind: 'person' },
    { id: 'teams', label: 'Teams + Outlook', sub: 'actionable approvals and receipt', col: 0, row: 1, kind: 'ui' },
    { id: 'mail', label: 'AP shared mailbox', sub: 'Logic Apps trigger', col: 0, row: 2, kind: 'ui' },
    { id: 'erp', label: 'Oracle EBS R12', sub: 'ExpressRoute / data gateway', col: 0, row: 3, kind: 'ext' },
    { id: 'edge', label: 'Front Door + WAF + APIM', sub: 'Static Web Apps', col: 1, row: 0, kind: 'edge' },
    { id: 'svc', label: 'FastAPI on Container Apps', sub: 'same container as the demo', col: 1, row: 1, kind: 'app' },
    { id: 'durable', label: 'Durable Functions', sub: 'receipt and approval waits', col: 1, row: 2, kind: 'app' },
    { id: 'logic', label: 'Logic Apps', sub: 'mailbox, schedules', col: 1, row: 3, kind: 'ops' },
    { id: 'agents', label: 'Foundry Agent Service', sub: 'orchestrator + connected agents', col: 2, row: 0, kind: 'agent', ai: true },
    { id: 'fn', label: 'OpenAPI tools on Functions', sub: 'Checks, Policy, Recommender', col: 2, row: 1, kind: 'agent' },
    { id: 'pg', label: 'Azure Database for PostgreSQL', sub: 'runs, decisions, cases, audit', col: 2, row: 2, kind: 'data' },
    { id: 'blob', label: 'Immutable Blob Storage', sub: 'PDFs, traces, evidence packs', col: 2, row: 3, kind: 'data' },
    { id: 'search', label: 'Azure AI Search', sub: 'policy grounding, history index', col: 3, row: 1, kind: 'data' },
    { id: 'obs', label: 'Monitor · Key Vault · Purview', sub: 'tracing, secrets, lineage', col: 3, row: 3, kind: 'ops' },
    { id: 'claude', label: 'Claude in Foundry', sub: 'Azure OpenAI as second model', col: 4, row: 0, kind: 'model', ai: true },
    { id: 'safety', label: 'AI Content Safety', sub: 'prompt shields, groundedness', col: 4, row: 1, kind: 'model' },
    { id: 'pub', label: 'EU VIES · OFAC · ECB', sub: 'egress allow-list', col: 4, row: 2, kind: 'ext' },
  ],
  flows: [
    { from: 'people', to: 'edge', n: 1, label: 'Entra ID token; app roles', data: 'Internal' },
    { from: 'mail', to: 'logic', n: 2, label: 'New invoice trigger', data: 'Confidential' },
    { from: 'logic', to: 'svc', n: 3, label: 'Intake and scheduled sweeps', data: 'Internal' },
    { from: 'edge', to: 'svc', n: 4, label: 'API calls via private endpoint', data: 'Internal' },
    { from: 'svc', to: 'agents', n: 5, label: 'Create run per invoice', data: 'Confidential' },
    { from: 'agents', to: 'fn', n: 6, label: 'OpenAPI tool calls', data: 'Confidential' },
    { from: 'agents', to: 'claude', n: 7, label: 'Reasoning, extraction, reasons', data: 'Confidential' },
    { from: 'claude', to: 'safety', n: 8, label: 'Shields and groundedness checks', data: 'Confidential' },
    { from: 'fn', to: 'search', n: 9, label: 'Similar lines, policy passages', data: 'Confidential' },
    { from: 'svc', to: 'pg', n: 10, label: 'State and audit events', data: 'Confidential' },
    { from: 'svc', to: 'durable', n: 11, label: 'Wait for receipt or approval', data: 'Internal' },
    { from: 'durable', to: 'teams', n: 12, label: 'Adaptive card to requester / approver', data: 'Internal' },
    { from: 'svc', to: 'erp', n: 13, label: 'AP and GL interface batches', data: 'Confidential' },
    { from: 'fn', to: 'pub', n: 14, label: 'Registry lookups', data: 'Public' },
    { from: 'svc', to: 'blob', n: 15, label: 'Documents and evidence, retained', data: 'Confidential' },
  ],
  notes: [
    'Teams approvals replace the QR phone view once a Mastercard tenant is available; the server-side role checks do not change.',
    'Foundry tracing records every tool call per run, giving audit the same evidence the demo’s run records show.',
  ],
}

export type AgentMeta = {
  id: string; name: string; question: string; step: string; trigger: string; decides: string[];
  inputs: string; outputs: string; guardrails: string[]; failure: string; human?: string; kind: 'deterministic' | 'model' | 'mixed'
}

export const AGENTS: AgentMeta[] = [
  { id: 'supervisor', name: 'Supervisor', question: 'In what order, and what is the status?', step: 'All', kind: 'mixed',
    trigger: 'An invoice arrives, is run by a reviewer, or something it depends on changes',
    decides: ['Runs every specialist in a fixed order', 'Applies status precedence: match to PO, held, awaiting receipt, needs coding, fast-track, recommended', 'Calls the investigator on exceptions', 'Asks Claude for the reviewer reason'],
    inputs: 'Intake record', outputs: 'Run record: steps, tool calls, findings, status, reason, policy and model versions',
    guardrails: ['Cannot approve, pay or edit master data', 'Every control always runs; none is skipped on confidence'],
    failure: 'A failed control holds the invoice with "check could not complete"; a model failure falls back to the template reason' },
  { id: 'intake', name: 'Intake and extraction', question: 'What does the invoice say?', step: 'Intake', kind: 'model',
    trigger: 'Every run', decides: ['Reads the PDF into a fixed schema with Claude', 'Cross-checks six key fields against the intake record', 'Translates to USD at the month-end rate'],
    inputs: 'PDF or portal/e-invoice record', outputs: 'Structured invoice; field agreement',
    guardrails: ['Schema-constrained output', 'Any field disagreement raises a warning for a person'],
    failure: 'Model unavailable: uses the intake-captured fields and says so' },
  { id: 'supplier', name: 'Supplier and validity', question: 'Should this be here, and is it valid?', step: 'Steps 1–2', kind: 'deterministic',
    trigger: 'Every run', decides: ['Routes intercompany and employee reimbursements out of AP', 'Matches the vendor master; OFAC screen', 'Mandatory fields, billed-to entity, currency, VAT via EU VIES', 'Duplicates across 18 months and the open queue', 'Open-PO match; PO policy'],
    inputs: 'Structured invoice, sender', outputs: 'Vendor match, validity, duplicates, PO findings',
    guardrails: ['Unknown supplier stops the run before any coding', 'Holds are released only by a person'],
    failure: 'Registry unreachable: uses the cached answer and labels its age', human: 'Vendor master onboards unknown suppliers' },
  { id: 'coding', name: 'Coding and treatment', question: 'What is it, where does it go?', step: 'Step 4', kind: 'mixed',
    trigger: 'Supplier is known and in scope', decides: ['Scores account and cost centre from similar past lines', 'Applies learned corrections', 'Splits by named cost centre or entity', 'Capitalise (per-unit threshold) or prepay', 'Cut-off against the closed period and its accruals', 'Use-tax accrual'],
    inputs: 'Invoice lines, supplier history, policies', outputs: 'Coding per line with calibrated confidence, evidence, treatment',
    guardrails: ['The language model never picks the account', 'Capitalisation is routed, not decided'],
    failure: 'No similar history: confidence drops into the needs-a-person band', human: 'AP specialist accepts or overrides; Fixed Asset Accounting decides capitalisation' },
  { id: 'price', name: 'Price', question: 'Is the price right?', step: 'Step 5', kind: 'deterministic',
    trigger: 'Every coded invoice', decides: ['Billed rates against the engagement letter by role', 'Fixed fee against the signed SOW', 'Legal matter budget consumed', 'Amount against the supplier median'],
    inputs: 'Invoice lines, contracts, budgets', outputs: 'Rate variances, budget share, SOW match',
    guardrails: ['Flags variances; never edits the invoice'], failure: 'No contract on file: says so and relies on supplier history' },
  { id: 'approval', name: 'Approval and receipt', question: 'Who asked, did we get it, who can approve?', step: 'Steps 3 and 6', kind: 'deterministic',
    trigger: 'Every coded invoice', decides: ['Identifies the requester (matter register, named contact, history)', 'Accepts existing receipt evidence or sends a confirmation task with SLA timers', 'Routes by category rules, amount tier, approval limits, SoD and delegates'],
    inputs: 'Coding, people directory, approval matrix', outputs: 'Requester, receipt status, approval chain',
    guardrails: ['The approval matrix is data, not prompt', 'Nobody approves their own spend'],
    failure: 'No requester found: escalates to the cost-centre owner, then the supplier', human: 'Requester confirms; approvers sign in order' },
  { id: 'risk', name: 'Payment risk', question: 'Is it safe to pay?', step: 'Step 7', kind: 'deterministic',
    trigger: 'Every coded invoice', decides: ['Amount against the supplier norm', 'Recent bank change without call-back', 'Remit-to mismatch, look-alike sender domain', 'Terms and open early-payment discounts'],
    inputs: 'Invoice, vendor master, bank change log', outputs: 'Risk signals, payment hold, discount',
    guardrails: ['High-severity signals always hold; never cleared automatically'], failure: 'Missing bank history: treated as unverified', human: 'Vendor master verifies by call-back' },
  { id: 'investigator', name: 'Investigator', question: 'Why was it stopped, and what next?', step: 'Exceptions', kind: 'model',
    trigger: 'Held, needs coding, unknown supplier, or an anomaly case', decides: ['Calls up to 8 read-only tools (vendor profile, bank log, history, invoice lookup, open POs, directory, journals, receivables)', 'Writes a summary with evidence citing the tool calls it made', 'Picks the next action from a fixed list'],
    inputs: 'Case file: invoice or case, findings', outputs: 'Summary, cited evidence, next action, confidence',
    guardrails: ['Read-only tools; cannot change status or write', 'Schema-checked; uncited evidence is dropped', 'Tool budget and 45-second deadline'],
    failure: 'Invalid output, budget or model failure: deterministic summary of the findings' },
  { id: 'anomaly', name: 'Anomaly sweep', question: 'What was miscoded after the fact?', step: 'Close', kind: 'deterministic',
    trigger: 'Month-end close; daily cash run', decides: ['Journals posted against how similar lines are coded', 'Duplicate accruals, self-approved entries', 'AP lines coded away from the supplier’s norm', 'Misapplied and unapplied cash with proposed matches'],
    inputs: 'Journals, AP subledger, receipts, AR', outputs: 'Cases with drafted fixes',
    guardrails: ['Proposes fixes; posts nothing', 'Suppliers legitimately coded two ways are not flagged'],
    failure: 'Cases stay open past SLA and show as overdue', human: 'Preparer submits, a different approver signs, then export to the ledger' },
]

export const MAPPING: { concern: string; repo: string; aws: string; azure: string }[] = [
  { concern: 'Front end', repo: 'Vercel CDN', aws: 'CloudFront + S3', azure: 'Static Web Apps' },
  { concern: 'Sign-in and roles', repo: 'Named sign-in, server-side roles', aws: 'Cognito + corporate IdP groups', azure: 'Entra ID app roles' },
  { concern: 'API service', repo: 'Vercel Python function', aws: 'ECS on Fargate', azure: 'Container Apps' },
  { concern: 'Agent orchestration', repo: 'Supervisor in Python', aws: 'Bedrock Agents supervisor', azure: 'Foundry Agent Service' },
  { concern: 'Agent tools', repo: 'Tool registry (typed, recorded)', aws: 'Action groups on Lambda', azure: 'OpenAPI tools on Functions' },
  { concern: 'Model', repo: 'Claude via Anthropic API', aws: 'Claude on Bedrock', azure: 'Claude in Foundry' },
  { concern: 'Safety', repo: 'Schema output, read-only investigator, fallbacks', aws: 'Bedrock Guardrails', azure: 'AI Content Safety' },
  { concern: 'Coding model', repo: 'Calibrated champion + challenger', aws: 'SageMaker endpoint or Lambda numpy', azure: 'Azure ML endpoint or Functions' },
  { concern: 'Policy grounding', repo: 'Versioned policies in state', aws: 'Bedrock Knowledge Bases', azure: 'AI Search' },
  { concern: 'Documents', repo: 'data/pdfs', aws: 'S3 with Object Lock', azure: 'Immutable Blob Storage' },
  { concern: 'State and audit log', repo: 'SQLite or Neon Postgres', aws: 'Aurora PostgreSQL', azure: 'Azure Database for PostgreSQL' },
  { concern: 'Waiting on people', repo: 'Receipt tasks + SLA sweep', aws: 'Step Functions task tokens', azure: 'Durable Functions' },
  { concern: 'Schedules', repo: 'Demo clock + on-request sweep', aws: 'EventBridge Scheduler', azure: 'Logic Apps' },
  { concern: 'Invoice intake', repo: 'Seeded mailbox and live upload', aws: 'SES inbound to S3', azure: 'Logic Apps mailbox trigger' },
  { concern: 'ERP', repo: 'Oracle R12 interface CSVs', aws: 'PrivateLink to Oracle EBS', azure: 'ExpressRoute to Oracle EBS' },
  { concern: 'Observability', repo: 'Operations page from run records', aws: 'CloudWatch, CloudTrail, X-Ray', azure: 'Azure Monitor, App Insights' },
]
