// Operational workflows as sequence diagrams. Each message names the endpoint or function that carries it in the
// demo; frames show the alternative and repeating paths; timers show the SLAs the service enforces.

export type Msg = { from: string; to: string; label: string; api?: string; ret?: boolean }
export type Frame = { frame: 'alt' | 'opt' | 'loop'; label: string; items: Item[]; elseLabel?: string; elseItems?: Item[] }
export type Timer = { timer: string; on: string }
export type Note = { note: string; over: string[] }
export type Item = Msg | Frame | Timer | Note
export type Participant = { id: string; label: string; kind: 'person' | 'system' | 'agent' | 'model' | 'data' | 'ext' }
export type Ops = { trigger: string; sla: string; raci: [string, string][]; controls: string[]; kpis: string[]; exceptions: string[]; systems: string[] }
export type Workflow = { id: string; name: string; purpose: string; participants: Participant[]; items: Item[]; ops: Ops }

const P = {
  mail: { id: 'mail', label: 'AP mailbox', kind: 'system' },
  ap: { id: 'ap', label: 'AP specialist', kind: 'person' },
  api: { id: 'api', label: 'Service', kind: 'system' },
  sup: { id: 'sup', label: 'Supervisor', kind: 'agent' },
  spec: { id: 'spec', label: 'Specialist agents', kind: 'agent' },
  tools: { id: 'tools', label: 'Tools + data', kind: 'data' },
  claude: { id: 'claude', label: 'Claude', kind: 'model' },
  inv: { id: 'inv', label: 'Investigator', kind: 'agent' },
  req: { id: 'req', label: 'Requester', kind: 'person' },
  appr: { id: 'appr', label: 'Approver', kind: 'person' },
  vm: { id: 'vm', label: 'Vendor master', kind: 'person' },
  sup2: { id: 'supp', label: 'Supplier', kind: 'ext' },
  gl: { id: 'gl', label: 'GL accountant', kind: 'person' },
  ctrl: { id: 'ctrl', label: 'Controller', kind: 'person' },
  cash: { id: 'cash', label: 'Cash application', kind: 'person' },
  proc: { id: 'proc', label: 'Procurement', kind: 'person' },
  fa: { id: 'fa', label: 'Fixed Assets', kind: 'person' },
  erp: { id: 'erp', label: 'Oracle EBS', kind: 'ext' },
  ds: { id: 'ds', label: 'Model pipeline', kind: 'data' },
  admin: { id: 'admin', label: 'Admin', kind: 'person' },
} satisfies Record<string, Participant>

export const WORKFLOWS: Workflow[] = [
  {
    id: 'intake', name: 'Intake and agent run', purpose: 'Every non-PO invoice is read and worked, every control in order, before a person spends time on it.',
    participants: [P.mail, P.ap, P.api, P.sup, P.spec, P.tools, P.claude],
    items: [
      { from: 'mail', to: 'api', label: 'Invoice arrives (email, portal, scan)', api: 'intake queue' },
      { from: 'ap', to: 'api', label: 'Run the agent on the mailbox', api: 'GET /api/mailbox/run' },
      { frame: 'loop', label: 'each new invoice', items: [
        { from: 'api', to: 'sup', label: 'process(item, trigger)', api: 'Supervisor.process' },
        { from: 'sup', to: 'spec', label: 'Intake: read the PDF', api: 'invoice.read' },
        { from: 'spec', to: 'claude', label: 'Extract to schema', api: 'llm.extract_pdf' },
        { from: 'claude', to: 'spec', label: 'Fields', ret: true },
        { from: 'sup', to: 'spec', label: 'Supplier, validity, PO, coding, price, receipt, risk, approval', api: 'specialists.py' },
        { from: 'spec', to: 'tools', label: '30–40 typed tool calls, each recorded', api: 'RunContext.call' },
        { from: 'tools', to: 'spec', label: 'Findings', ret: true },
        { from: 'sup', to: 'claude', label: 'Write the reviewer reason', api: 'llm.explain' },
        { from: 'sup', to: 'api', label: 'Run record + status', ret: true },
      ] },
      { from: 'api', to: 'ap', label: 'Rows flip live; status per invoice', ret: true, api: 'SSE events' },
    ],
    ops: { trigger: 'Invoice received; reviewer run; overnight batch', sla: 'Worked within minutes of arrival; under 10 s per invoice on screen',
      raci: [['AP specialist', 'A'], ['Agent', 'R'], ['Controllership', 'I']],
      controls: ['Every control runs in fixed order', 'Extraction cross-checked against intake', 'Run record with policy and model version'],
      kpis: ['Invoices worked per hour', 'Fast-track share', 'Run latency p50/p95'],
      exceptions: ['Model unavailable → intake fields and template reason', 'Registry down → cached answer, labelled'], systems: ['AP mailbox', 'Agent service', 'Claude'] },
  },
  {
    id: 'investigate', name: 'Exception investigation', purpose: 'When a control stops an invoice, Claude checks the facts with read-only tools and says what a person should do next.',
    participants: [P.sup, P.inv, P.claude, P.tools, P.ap],
    items: [
      { from: 'sup', to: 'inv', label: 'Status is HELD / NEEDS_CODING / onboarding', api: 'investigate(ctx, r)' },
      { from: 'inv', to: 'claude', label: 'Case file + read-only tool list', api: 'messages.create(tools)' },
      { frame: 'loop', label: 'up to 8 calls, 45 s', items: [
        { from: 'claude', to: 'inv', label: 'tool_use (e.g. bank_change_log)', ret: true },
        { from: 'inv', to: 'tools', label: 'Recorded call [T31]', api: 'RunContext.call' },
        { from: 'tools', to: 'inv', label: 'Result', ret: true },
        { from: 'inv', to: 'claude', label: 'tool_result tagged with call id' },
      ] },
      { from: 'claude', to: 'inv', label: 'Summary, cited evidence, next action (schema)', ret: true },
      { note: 'Uncited evidence dropped; actions outside the list rejected', over: ['inv'] },
      { frame: 'alt', label: 'valid answer', items: [{ from: 'inv', to: 'sup', label: 'Investigation (live), cached for replay', ret: true }],
        elseLabel: 'invalid / budget / model down', elseItems: [{ from: 'inv', to: 'sup', label: 'Deterministic summary of findings', ret: true }] },
      { from: 'sup', to: 'ap', label: 'Findings card with clickable citations', ret: true },
    ],
    ops: { trigger: 'Any exception status', sla: 'Under 45 s; replayed instantly once cached',
      raci: [['AP specialist', 'A'], ['Investigator', 'R'], ['Vendor master', 'C']],
      controls: ['Read-only tools only', 'Evidence must cite real tool calls', 'Fixed action list'],
      kpis: ['Exceptions investigated', 'Time to resolution', 'Share of fallback summaries'],
      exceptions: ['Refusal → fallback', 'Tool error → reported as is_error, loop continues'], systems: ['Agent service', 'Claude'] },
  },
  {
    id: 'receipt', name: 'Receipt confirmation and escalation', purpose: 'No PO means no goods receipt: existing evidence first, then the requester, with timers so nothing sits unclaimed.',
    participants: [P.spec, P.tools, P.api, P.req, P.appr, P.sup2],
    items: [
      { from: 'spec', to: 'tools', label: 'Standing rule?', api: 'receipt.requirement' },
      { from: 'spec', to: 'tools', label: 'Existing evidence? (asset scan, goods-in, signed order form)', api: 'receipt.find_evidence' },
      { frame: 'alt', label: 'evidence found', items: [{ from: 'tools', to: 'spec', label: 'Receipt evidenced; no task', ret: true }],
        elseLabel: 'no evidence', elseItems: [
          { from: 'api', to: 'req', label: 'Confirm-receipt task (phone or desktop)', api: 'POST /receipt/request' },
          { timer: '3 business days', on: 'api' },
          { from: 'api', to: 'req', label: 'Reminder', api: 'apply_sla' },
          { timer: '5 business days', on: 'api' },
          { from: 'api', to: 'appr', label: 'Escalate to cost-centre owner', api: 'RECEIPT_ESCALATED' },
          { timer: '8 business days', on: 'api' },
          { from: 'api', to: 'supp', label: 'Ask supplier for the name of whoever ordered', api: 'SUPPLIER_CONTACTED' },
        ] },
      { from: 'req', to: 'api', label: 'Confirm (only the requester can)', api: 'POST /receipt/confirm' },
      { from: 'api', to: 'spec', label: 'Status moves on; re-run shows the diff', ret: true },
    ],
    ops: { trigger: 'Receipt required and not covered', sla: 'Reminder 3, escalate 5, supplier 8 business days',
      raci: [['Requester', 'R'], ['Cost-centre owner', 'A'], ['AP specialist', 'I']],
      controls: ['Approval locked until receipt', 'Only the requester confirms', 'Every reminder and escalation audited'],
      kpis: ['Days to confirmation', 'Share evidenced without a task', 'Escalations'],
      exceptions: ['Unclaimed → supplier contact', 'Wrong requester → reassign on escalation'], systems: ['Agent service', 'Phone view / Teams'] },
  },
  {
    id: 'approval', name: 'Approval routing (DoA, SoD, delegates)', purpose: 'The approval matrix applied the same way every time; only the next approver can act.',
    participants: [P.ap, P.api, P.spec, P.tools, P.appr, P.erp],
    items: [
      { from: 'spec', to: 'tools', label: 'Category rules, amount tier, limits, SoD, delegates', api: 'approval.route' },
      { note: 'Requester skipped (SoD); below-limit skipped (DoA); out-of-office → delegate', over: ['tools'] },
      { from: 'ap', to: 'api', label: 'Accept / override with reason', api: 'POST /decision' },
      { frame: 'loop', label: 'each approver in order', items: [
        { from: 'api', to: 'appr', label: 'Waiting for you (inbox)' },
        { from: 'appr', to: 'api', label: 'Approve', api: 'POST /approve' },
        { frame: 'opt', label: 'out of turn', items: [{ from: 'api', to: 'appr', label: '403 + ACCESS_DENIED audit', ret: true }] },
      ] },
      { from: 'api', to: 'erp', label: 'Final approval → AP interface batch', api: 'AP_INVOICES_INTERFACE' },
    ],
    ops: { trigger: 'Invoice submitted by AP', sla: 'Per approver: 2 business days',
      raci: [['Approver', 'A'], ['AP specialist', 'R'], ['Internal audit', 'I']],
      controls: ['Server-enforced next-approver check', 'SoD: requester never approves', 'Limit check on final approver'],
      kpis: ['Cycle time receipt → approval', 'Reroutes for SoD', 'Approvals out of turn refused'],
      exceptions: ['Approver absent → delegate', 'Limit too low → next level'], systems: ['Agent service', 'Oracle EBS'] },
  },
  {
    id: 'posting', name: 'Posting to Oracle R12', purpose: 'Standard open-interface files, the same upload path the CoE uses today; no screen-scraping.',
    participants: [P.api, P.tools, P.erp, P.ap],
    items: [
      { from: 'api', to: 'tools', label: 'Approved invoices with final coding', api: 'export_ap' },
      { from: 'tools', to: 'api', label: 'AP_INVOICES_INTERFACE + LINES (group id)', ret: true, api: 'exports.ap_interface' },
      { from: 'api', to: 'erp', label: 'Upload; Payables Open Interface Import', api: 'GET /exports/ap-interface/{part}' },
      { from: 'erp', to: 'api', label: 'Import report (rejections)', ret: true },
      { frame: 'opt', label: 'rejected lines', items: [{ from: 'api', to: 'ap', label: 'Back to the queue with the R12 reason' }] },
    ],
    ops: { trigger: 'Final approval', sla: 'Next import cycle', raci: [['AP specialist', 'R'], ['AP manager', 'A']],
      controls: ['Group id per batch', 'Approved only', 'Distribution segments from approved coding'],
      kpis: ['First-pass import rate', 'Lines per batch'], exceptions: ['Import rejection → re-queue'], systems: ['Oracle EBS R12'] },
  },
  {
    id: 'risk', name: 'Payment-risk hold and call-back', purpose: 'Stop the classic bank-change fraud before the payment run, and release only on a verified call-back.',
    participants: [P.spec, P.tools, P.inv, P.vm, P.sup2, P.api],
    items: [
      { from: 'spec', to: 'tools', label: 'Amount vs norm, bank change, remit-to, look-alike domain, terms', api: 'risk.payment_risk' },
      { from: 'tools', to: 'spec', label: 'High-severity signals → HOLD', ret: true },
      { from: 'spec', to: 'inv', label: 'Investigate the hold' },
      { from: 'inv', to: 'vm', label: 'Summary: look-alike domain changed the bank details; call back', ret: true },
      { from: 'vm', to: 'supp', label: 'Call on the number already on file' },
      { frame: 'alt', label: 'supplier confirms the change', items: [{ from: 'vm', to: 'api', label: 'Verified', api: 'POST /vendors/{id}/callback' },
        { from: 'api', to: 'spec', label: 'Re-run: bank signal cleared, amount still reviewed' }],
      elseLabel: 'supplier never asked', elseItems: [{ from: 'vm', to: 'api', label: 'Fraud', api: 'callback(outcome=fraud)' },
        { from: 'api', to: 'api', label: 'Reject invoice, reverse the change, notify security' }] },
    ],
    ops: { trigger: 'PAYMENT_RISK hold', sla: 'Call-back within 1 business day; excluded from payment runs meanwhile',
      raci: [['Vendor master', 'R'], ['Treasury', 'A'], ['AP specialist', 'I']],
      controls: ['Never auto-cleared', 'Call-back on master-data number only', 'Outcome audited'],
      kpis: ['Holds released vs rejected', 'Time on hold'], exceptions: ['Unreachable supplier → stays held'], systems: ['Vendor master', 'Agent service'] },
  },
  {
    id: 'reclass', name: 'Month-end anomaly → reclass → GL', purpose: 'Catch miscoding wherever it was keyed and correct it through a prepared, approved, balanced batch.',
    participants: [P.api, P.spec, P.gl, P.ctrl, P.erp],
    items: [
      { from: 'api', to: 'spec', label: 'Sweep journals and AP subledger', api: 'scan_journals / scan_ap_ledger' },
      { from: 'spec', to: 'api', label: 'Cases with drafted reclass (Dr suggested / Cr posted)', ret: true },
      { from: 'gl', to: 'api', label: 'Review, adjust, prepare', api: 'POST /cases/{id}/prepare' },
      { note: 'Whoever posted the original entry cannot prepare its fix', over: ['api'] },
      { from: 'ctrl', to: 'api', label: 'Approve (not the preparer)', api: 'POST /cases/{id}/approve' },
      { frame: 'opt', label: 'needs more', items: [{ from: 'ctrl', to: 'gl', label: 'Send back with reason', api: 'send-back' }] },
      { from: 'ctrl', to: 'api', label: 'Post approved corrections', api: 'POST /cases/export (gl)' },
      { from: 'api', to: 'api', label: 'Control totals: Dr = Cr or refuse' },
      { from: 'api', to: 'erp', label: 'GL_INTERFACE batch (OCT-26, prior-period ref)' },
      { from: 'api', to: 'spec', label: 'Approved AP reclass becomes history (learning)', ret: true },
    ],
    ops: { trigger: 'Close WD1; on request', sla: '3 business days for journals, 5 for AP',
      raci: [['GL accountant', 'R'], ['Controller', 'A'], ['Internal audit', 'I']],
      controls: ['Preparer ≠ approver ≠ original poster', 'Balanced batch or no export', 'Dismissal needs a reason; “valid as posted” suppresses the pattern'],
      kpis: ['Reclasses avoided at close', 'Precision of the sweep', 'Cases overdue'], exceptions: ['Unbalanced batch refused'], systems: ['Oracle EBS GL'] },
  },
  {
    id: 'cash', name: 'Cash misapplication → reapply', purpose: 'Find the 1–2% that auto-apply gets wrong and fix it with a reviewed re-application.',
    participants: [P.api, P.spec, P.inv, P.cash, P.erp],
    items: [
      { from: 'api', to: 'spec', label: 'Scan the day’s settlement receipts', api: 'scan_cash' },
      { from: 'spec', to: 'api', label: 'Misapplied (transposed customer), double applied, unapplied with match', ret: true },
      { frame: 'opt', label: 'unclear', items: [{ from: 'cash', to: 'inv', label: 'Investigate: customer items, remittance', api: 'ar.customer_items' }] },
      { from: 'cash', to: 'api', label: 'Prepare unapply/reapply; bulk-prepare matches ≥ 95%', api: 'bulk-prepare' },
      { from: 'cash', to: 'api', label: 'Lead approves', api: 'approve' },
      { from: 'api', to: 'erp', label: 'Receipt reapplication file', api: 'export (cash)' },
    ],
    ops: { trigger: 'Daily after auto-apply', sla: 'Same business day', raci: [['Cash application', 'R'], ['Cash application lead', 'A']],
      controls: ['Preparer ≠ approver ≠ original applier', 'Confidence threshold for bulk'], kpis: ['Unapplied cash $', 'Auto-apply rate', 'Misapplications caught'],
      exceptions: ['Short / over pay → adjustment activity'], systems: ['Oracle AR', 'Lockbox'] },
  },
  {
    id: 'po', name: 'PO compliance → blanket PO', purpose: 'Shrink non-PO volume at source, not just process it faster.',
    participants: [P.spec, P.tools, P.api, P.proc],
    items: [
      { from: 'spec', to: 'tools', label: 'Category and amount against PO policy', api: 'po.policy' },
      { from: 'tools', to: 'spec', label: 'Should have been a PO (logged, still processed)', ret: true },
      { from: 'api', to: 'api', label: 'Aggregate 18 months by category and supplier', api: 'procurement()' },
      { from: 'proc', to: 'api', label: 'Request blanket PO or standing rule', api: 'POST /procurement/requests' },
      { from: 'api', to: 'proc', label: 'Request in procurement queue; future invoices match to PO', ret: true },
    ],
    ops: { trigger: 'Every invoice; monthly review', sla: 'Monthly', raci: [['Procurement', 'A'], ['Requesters', 'C'], ['AP', 'I']],
      controls: ['Breach logged with rule'], kpis: ['Non-PO spend moved onto POs', 'Breach $ by category'], exceptions: ['Exempt categories'], systems: ['Coupa / R12 PO'] },
  },
  {
    id: 'treatment', name: 'Prepaid, capitalisation, cut-off and tax', purpose: 'Join P2P to R2R so the period is right the first time.',
    participants: [P.spec, P.tools, P.fa, P.gl, P.erp],
    items: [
      { from: 'spec', to: 'tools', label: 'Per-unit cost vs asset threshold', api: 'recommend_line (capitalise)' },
      { frame: 'alt', label: 'over threshold', items: [{ from: 'spec', to: 'fa', label: 'Route to Fixed Assets (they decide)' }],
        elseLabel: 'multi-month service', elseItems: [{ from: 'spec', to: 'gl', label: 'Prepaid + amortisation journal drafted', api: 'exports.gl_amortisation' }] },
      { from: 'spec', to: 'tools', label: 'Closed period? accrual on file?', api: 'cutoff.check' },
      { frame: 'opt', label: 'unaccrued ≥ materiality', items: [{ from: 'spec', to: 'gl', label: 'Report out-of-period expense' }] },
      { from: 'spec', to: 'tools', label: 'Taxable goods, no tax charged?', api: 'tax.use_tax' },
      { from: 'gl', to: 'erp', label: 'Amortisation / use-tax accrual via GL_INTERFACE' },
    ],
    ops: { trigger: 'Coding step', sla: 'Before period close', raci: [['Fixed Assets', 'A'], ['GL accountant', 'R'], ['Tax', 'C']],
      controls: ['Capitalisation routed, not decided', 'Materiality threshold from policy'], kpis: ['Prior-period adjustments', 'Use tax accrued'],
      exceptions: ['Mixed lines → split'], systems: ['Oracle FA', 'Oracle GL'] },
  },
  {
    id: 'learning', name: 'Learning loop and retraining', purpose: 'Corrections become history; the model is re-measured before it changes.',
    participants: [P.ap, P.api, P.tools, P.ds, P.admin],
    items: [
      { from: 'ap', to: 'api', label: 'Override with reason', api: 'decision(override)' },
      { from: 'api', to: 'tools', label: 'Correction stored for this supplier and line', api: 'learned:{vendor}:{line}' },
      { from: 'api', to: 'api', label: 'Earlier runs marked stale' },
      { from: 'ap', to: 'api', label: 'Re-run: diff shows the learned change' },
      { frame: 'loop', label: 'monthly or on drift', items: [
        { from: 'ds', to: 'tools', label: 'Time-split back-test, champion vs challenger', api: 'scripts/train.py' },
        { from: 'ds', to: 'admin', label: 'Metrics, calibration, proposed bands', ret: true },
        { from: 'admin', to: 'api', label: 'Adopt bands as a new policy version', api: 'POST /policies' },
      ] },
    ],
    ops: { trigger: 'Overrides; override rate > 8% for 2 weeks; PSI > 0.2', sla: 'Monthly review',
      raci: [['Model owner (CoE)', 'R'], ['Controllership', 'A'], ['Model risk', 'C']],
      controls: ['Regression floor blocks deploy', 'Bands only change by policy version'], kpis: ['First-time-right', 'Override rate', 'Calibration error'],
      exceptions: ['Metric regression → keep current model'], systems: ['Model pipeline'] },
  },
  {
    id: 'upload', name: 'Live upload', purpose: 'Prove it on an invoice nobody prepared.',
    participants: [P.ap, P.api, P.claude, P.sup, P.spec],
    items: [
      { from: 'ap', to: 'api', label: 'Upload a PDF (≤ 8 MB)', api: 'POST /api/wildcard' },
      { from: 'api', to: 'claude', label: 'Read it live, bypassing the cache', api: 'extract_pdf(force_live)' },
      { from: 'claude', to: 'api', label: 'Fields', ret: true },
      { from: 'api', to: 'sup', label: 'Run every control', api: 'run_events' },
      { from: 'sup', to: 'spec', label: 'Same specialists, same tools' },
      { from: 'sup', to: 'ap', label: 'Streamed to screen', ret: true },
    ],
    ops: { trigger: 'Someone in the room uploads an invoice', sla: 'Under 30 s', raci: [['AP specialist', 'R']],
      controls: ['PDF only, size limit', 'Unknown supplier stops at step 1'], kpis: ['—'], exceptions: ['Unreadable PDF → clear error'], systems: ['Claude'] },
  },
]
